version: "3.9"

services:
  api:
    image: bekabeka/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    volumes:
      - ./docker_config.py:/code/default_config.py
    platform: linux/amd64
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
